name: Go Build & Deploy

on:
  push:
    branches:
      - master
      - main
      - dev
      - qa

permissions:
  id-token: write #for OIDC

  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go

        uses: actions/checkout@v2

        with:
          go-version: "1.21.3"

      - name: Install Deps #Deps will be automatically installed in the build phase

        run: |

          go version

      - name: Build Project

        run: go build main.go

      - name: Run vet

        run: go vet .

  deploy:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - uses: actions/checkout@v2

      - name: Initializing AWS Credentials

        uses: aws-actions/configure-aws-credentials@v1

        with:
          role-to-assume: ${{ secrets.IDENTITY_PROVIDER_ARN }}

          aws-region: us-east-1

      - name: Deploy to Lambda

        run: |

          echo "LAMBDA -> $vars.LAMBDA_FUNCTION_NAME" 

          zip -j main.zip ./main 

          aws lambda update-function-code --function-name=${{vars.LAMBDA_FUNCTION_NAME}}
